services:
  opencart:
    image: ghcr.io/chitzi/ivo-portainer-opencart:latest
    container_name: portainer_opencart_demo
    ports:
      - "8090:80"
    environment:
      OPENCART_HOST: ${OPENCART_HOST:-localhost}
      OPENCART_PORT: ${OPENCART_PORT:-:8090}
      OPENCART_DATABASE_HOST: mariadb_opencart_demo
      OPENCART_DATABASE_USER: bn_opencart
      OPENCART_DATABASE_PASSWORD: ""
      OPENCART_DATABASE_NAME: bitnami_opencart
    volumes:
      - opencart_demo_data:/var/www/html
    depends_on:
      - mariadb_opencart_demo
    restart: unless-stopped

  mariadb_opencart_demo:
    image: bitnami/mariadb:latest
    container_name: portainer_opencart_demo_db
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      MARIADB_USER: bn_opencart
      MARIADB_DATABASE: bitnami_opencart
    volumes:
      - mariadb_opencart_demo_data:/bitnami/mariadb
    restart: unless-stopped

volumes:
  opencart_demo_data:
  mariadb_opencart_demo_data:
